#!/bin/bash

USER_UID=`id -u`
USER_GID=`id -g`

CONTAINER_HOME=$HOME

docker run \
  -i \
  --rm \
  --read-only \
  --user "$USER_UID:$USER_GID" \
  --workdir `pwd` \
  -e HOME=$CONTAINER_HOME \
  -e DISPLAY=unix$DISPLAY \
  -e GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-2.0/gtkrc \
  -v $HOME:$CONTAINER_HOME \
  -v $CONTAINER_HOME/.config/gtk-3.0 \
  -v /usr/share/fonts:/usr/share/fonts:ro \
  -v /media:/media:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  mliszcz/atom \
  "$@" \
  >/dev/null 2>&1 &
