#!/bin/bash

USER_UID=`id -u`
USER_GID=`id -g`

# use AUDIO_GID group for ALSA output

CONTAINER_HOME=$HOME

docker run \
  -it \
  --rm \
  --user "$USER_UID:$USER_GID" \
  -e HOME=$CONTAINER_HOME \
  -e DISPLAY=unix$DISPLAY \
  -e GTK_THEME=Adwaita:dark \
  -v $HOME:$CONTAINER_HOME \
  -v $CONTAINER_HOME/.config/gtk-3.0 \
  -v /usr/share/fonts:/usr/share/fonts:ro \
  -v /media:/media:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  mliszcz/atom
